export const plants = [
  {
    id: "223757",
    scientific_name: "Anthurium beltianum",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1952",
    author: "Standl. & L.O.Williams",
    bibliography: "Ceiba 3: 103 (1952)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Nicaragua",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104777",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15120-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2873269",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium beltianum",
  },
  {
    id: "223758",
    scientific_name: "Anthurium berriozabalense",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1952",
    author: "Matuda",
    bibliography: "Anales Inst. Biol. Univ. Nac. México 22: 380 (1952)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Belize,Mexico Southeast,Mexico Southwest",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104778",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15121-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872935",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium berriozabalense",
  },
  {
    id: "223764",
    scientific_name: "Anthurium conspicuum",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1907",
    author: "Sodiro",
    bibliography: "Anturios Ecuator., Suppl. 2: 22 (1907)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Ecuador",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104789",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:1197383-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2873220",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium conspicuum",
  },
  {
    id: "223766",
    scientific_name: "Anthurium crassivenium",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1898",
    author: "Engl.",
    bibliography: "Bot. Jahrb. Syst. 25: 390 (1898)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Colombia",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104791",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15217-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872246",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium crassivenium",
  },
  {
    id: "223769",
    scientific_name: "Anthurium fontoides",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1953",
    author: "R.E.Schult.",
    bibliography: "Bot. Mus. Leafl. 16: 60 (1953)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Colombia",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104797",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15284-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872493",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium fontoides",
  },
  {
    id: "223771",
    scientific_name: "Anthurium geniculatum",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1903",
    author: "Sodiro",
    bibliography: "Anturios Ecuator., Suppl. 1: 2 (1903)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Ecuador",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104801",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15298-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2873203",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium geniculatum",
  },
  {
    id: "223783",
    scientific_name: "Anthurium intermedium",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1841",
    author: "Kunth",
    bibliography: "Enum. Pl. 3: 70 (1841)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "http://d2seqvvyy3b8p2.cloudfront.net/73acd9d1edeced3d8ac30e20da888aea.jpg",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Anthurium erythropodum,Anthurium leptostachyum,Anthurium rubricaule,Anthurium olfersianum var. acutangulum,Anthurium harrisii var. intermedium,Anthurium harrisii var. erythropodum,Anthurium olfersianum var. leptostachyum,Anthurium mandiocanum,Anthurium beyrichianum,Anthurium harrisii var. beyrichianum,Anthurium harrisii f. beyrichianum",
    distributions: "Brazil Northeast,Brazil Southeast",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2100629",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:84930-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872921",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium intermedium",
  },
  {
    id: "223785",
    scientific_name: "Anthurium herthae",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1940",
    author: "K.Krause",
    bibliography: "Notizbl. Bot. Gart. Berlin-Dahlem 15: 38 (1940)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Ecuador",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104816",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15334-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872266",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium herthae",
  },
  {
    id: "223787",
    scientific_name: "Anthurium huixtlense",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1950",
    author: "Matuda",
    bibliography: "Revista Soc. Mex. Hist. Nat. 11: 91 (1950)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Anthurium bochilense",
    distributions:
      "Belize,El Salvador,Guatemala,Honduras,Mexico Gulf,Mexico Southeast,Mexico Southwest,Nicaragua",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104821",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15347-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2872354",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium huixtlense",
  },
  {
    id: "223789",
    scientific_name: "Anthurium lanjouwii",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1966",
    author: "A.M.E.Jonker & Jonker",
    bibliography: "Acta Bot. Neerl. 15: 133 (1966)",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "French Guiana,Suriname",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104829",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15384-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2873664",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium lanjouwii",
  },
  {
    id: "222376",
    scientific_name: "Philodendron gloriosum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1876",
    author: "André",
    bibliography: "Ill. Hort. 23: 194 (1876)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/fddd1fc25efcfb66303984f14a397aab87556848",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Anthurium gloriosum",
    distributions: "Colombia,Hawaii",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2103225",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87777-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron gloriosum André",
    url_gbif: "https://www.gbif.org/species/2870786",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron gloriosum",
  },
  {
    id: "222599",
    scientific_name: "Philodendron maximum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1913",
    author: "K.Krause",
    bibliography: "H.G.A.Engler (ed.), Pflanzenr., IV, 23Db: 49 (1913)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "http://d2seqvvyy3b8p2.cloudfront.net/a98f926d58765dfa6c93ec8cf31b4c08.jpg",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Bolivia,Brazil North,Brazil West-Central,Ecuador,Peru",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2103465",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:193105-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2871298",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron maximum",
  },
  {
    id: "222839",
    scientific_name: "Pothos rubescens",
    rank: "species",
    genus: "Pothos",
    family: "Araceae",
    year: "",
    author: "Link & Otto ex Steud.",
    bibliography:
      "Nomenclator Botanicus. Editio secunda 2: 391. 1841. (Nomencl. Bot. (ed. 2))",
    common_name: "",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Anthurium rubescens",
    distributions: "",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2103785",
    url_tela_botanica: "",
    url_powo: "",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/5532185",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Pothos rubescens",
  },
  {
    id: "222305",
    scientific_name: "Monstera obliqua",
    rank: "species",
    genus: "Monstera",
    family: "Araceae",
    year: "1845",
    author: "Miq.",
    bibliography: "Linnaea 18: 79 (1845)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/8835c6090a7d1acc57213d2e97be8c04c13ff988",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Heteropsis obliqua,Monstera expilata,Monstera killipii,Monstera fendleri,Monstera falcifolia var. latifolia,Monstera falcifolia,Monstera obliqua var. expilata,Monstera unilatera,Monstera sagotiana,Monstera microstachys,Monstera snethlagei",
    distributions:
      "Bolivia,Brazil North,Brazil Northeast,Brazil West-Central,Colombia,Costa Rica,Ecuador,French Guiana,Guyana,Panamá,Peru,Suriname,Trinidad-Tobago,Venezuela",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2103143",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87525-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Monstera obliqua Miq.",
    url_gbif: "https://www.gbif.org/species/2868185",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Monstera obliqua",
  },
  {
    id: "224091",
    scientific_name: "Monstera minima",
    rank: "species",
    genus: "Monstera",
    family: "Araceae",
    year: "1977",
    author: "Madison",
    bibliography: "Contr. Gray Herb. 207: 72 (1977)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/0744cd898f7187d0ca5cce0af45c9b65ad3a5295",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Colombia,Panamá",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2105250",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:163942-2",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Monstera minima Madison",
    url_gbif: "https://www.gbif.org/species/2868240",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Monstera minima",
  },
  {
    id: "103782",
    scientific_name: "Allocasuarina acutivalvis",
    rank: "species",
    genus: "Allocasuarina",
    family: "Casuarinaceae",
    year: "1982",
    author: "(F.Muell.) L.A.S.Johnson",
    bibliography: "J. Adelaide Bot. Gard. 6: 74 (1982)",
    common_name: "",
    family_common_name: "She-oak family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Casuarina acutivalvis",
    distributions: "Western Australia",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=ALAC8",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:909935-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2891875",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Allocasuarina acutivalvis",
  },
  {
    id: "103786",
    scientific_name: "Allocasuarina corniculata",
    rank: "species",
    genus: "Allocasuarina",
    family: "Casuarinaceae",
    year: "1982",
    author: "(F.Muell.) L.A.S.Johnson",
    bibliography: "J. Adelaide Bot. Gard. 6: 74 (1982)",
    common_name: "",
    family_common_name: "She-oak family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Casuarina corniculata,Casuarina horrida",
    distributions: "Western Australia",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=ALCO15",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:909937-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2891825",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Allocasuarina corniculata",
  },
  {
    id: "103804",
    scientific_name: "Allocasuarina torulosa",
    rank: "species",
    genus: "Allocasuarina",
    family: "Casuarinaceae",
    year: "1982",
    author: "(Aiton) L.A.S.Johnson",
    bibliography: "J. Adelaide Bot. Gard. 6: 79 (1982)",
    common_name: "Forest-oak",
    family_common_name: "She-oak family",
    image_url:
      "https://bs.floristic.org/image/o/bc6c74365586535dfd1d85ce9adb7b6575ec74be",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Casuarina torulosa,Casuarina tenuissima,Casuarina lugubris,Casuarina ericoides,Casuarina torulosa f. gracilior",
    distributions: "New South Wales,Queensland",
    common_names: "Forest she-oak,Forest-oak,River-oak,Rose she-oak",
    url_usda: "https://plants.usda.gov/core/profile?symbol=ALTO5",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:909968-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Allocasuarina torulosa (Aiton) L.A.S.Johnson",
    url_gbif: "https://www.gbif.org/species/2891868",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Allocasuarina torulosa",
  },
  {
    id: "165579",
    scientific_name: "Philodendron consanguineum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1856",
    author: "Schott",
    bibliography: "Syn. Aroid.: 88 (1856)",
    common_name: "Rascagarganta",
    family_common_name: "Arum family",
    image_url:
      "http://d2seqvvyy3b8p2.cloudfront.net/eec255b5e26d1154597e8f7abe0674ef.jpg",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine, Forb/herb",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Philodendron angustatum,Philodendron krebsii,Philodendron marginatum,Philodendron fuertesii,Philodendron urbanianum,Philodendron wrightii",
    distributions:
      "Cuba,Dominican Republic,Haiti,Leeward Is.,Puerto Rico,Windward Is.",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHCO23",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87695-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2870653",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en:
      "https://en.wikipedia.org/wiki/Philodendron consanguineum",
  },
  {
    id: "165582",
    scientific_name: "Philodendron cordatum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1856",
    author: "Kunth ex Schott",
    bibliography: "Syn. Aroid.: 95 (1856)",
    common_name: "Heartleaf philodendron",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/78e75ce81eebbcae95af52b21fb573ac6edc60e7",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Arum cordatum,Philodendron apparicioi",
    distributions: "Brazil Southeast,Brazil West-Central",
    common_names: "Heartleaf philodendron",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHCO41",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77073767-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron cordatum Kunth ex Schott",
    url_gbif: "https://www.gbif.org/species/2871314",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron cordatum",
  },
  {
    id: "165583",
    scientific_name: "Philodendron fragrantissimum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1839",
    author: "(Hook.) G.Don",
    bibliography: "R.Sweet, Hort. Brit., ed. 3: 632 (1839)",
    common_name: "Shortstem philodendron",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/a349fb0046da6d8cb6a374aeffbe343ea4d1d4c0",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine, Forb/herb",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Philodendron brevilaminatum,Philodendron poeppigii,Philodendron latipes,Philodendron demerarae,Caladium fragrantissimum,Philodendron clementis,Arosma obtusifolia,Philodendron accrescens",
    distributions:
      "Belize,Bolivia,Brazil North,Brazil Northeast,Brazil Southeast,Colombia,Costa Rica,Cuba,Ecuador,French Guiana,Guatemala,Guyana,Honduras,Nicaragua,Panamá,Peru,Suriname,Trinidad-Tobago,Venezuela",
    common_names: "Shortstem philodendron",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHFR6",
    url_tropicos: "http://legacy.tropicos.org/Name/2103220",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87769-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron fragrantissimum (Hook.) G.Don",
    url_gbif: "https://www.gbif.org/species/2870944",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en:
      "https://en.wikipedia.org/wiki/Philodendron fragrantissimum",
  },
  {
    id: "165584",
    scientific_name: "Philodendron giganteum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1856",
    author: "Schott",
    bibliography: "Syn. Aroid.: 89 (1856)",
    common_name: "Giant philodendron",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/7ea7a0842d556c343209d4efcc4d3c6513a07869",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions:
      "Brazil North,Dominican Republic,Leeward Is.,Puerto Rico,Trinidad-Tobago,Venezuela,Windward Is.",
    common_names: "Giant philodendron,Chinabush",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHGI2",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87774-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron giganteum Schott",
    url_gbif: "https://www.gbif.org/species/2870862",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron giganteum",
  },
  {
    id: "165585",
    scientific_name: "Philodendron hederaceum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1829",
    author: "(Jacq.) Schott",
    bibliography: "Wiener Z. Kunst 3: 780 (1829)",
    common_name: "Vilevine",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/1ed12b222eab16916c9efb5cb0de9da698b53f3b",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine, Forb/herb",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Arum hederaceum",
    distributions:
      "Belize,Bolivia,Brazil North,Brazil Northeast,Brazil South,Brazil Southeast,Cayman Is.,Central American Pac,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,El Salvador,Guatemala,Honduras,Jamaica,Leeward Is.,Mexico Central,Mexico Gulf,Mexico Northeast,Mexico Southeast,Mexico Southwest,Nicaragua,Panamá,Peru,Puerto Rico,Suriname,Trinidad-Tobago,Venezuela,Windward Is.,Seychelles,French Guiana,Guyana",
    common_names: "Heart-leaf philodendron,Vilevine",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHHE17",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87797-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron hederaceum (Jacq.) Schott",
    url_gbif: "https://www.gbif.org/species/2871003",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron hederaceum",
  },
  {
    id: "165586",
    scientific_name: "Philodendron hederaceum var. hederaceum",
    rank: "var",
    genus: "Philodendron",
    family: "Araceae",
    year: "1829",
    author: "Schott (Jacq.)",
    bibliography: "Wiener Z. Kunst 3: 780 (1829)",
    common_name: "vilevine",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Forb/herb, Vine",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Philodendron micans,Philodendron scandens,Philodendron cuspidatum,Philodendron subsessile,Philodendron scaberulum,Philodendron prieurianum,Philodendron micans var. brevipes,Philodendron micans var. microphyllum,Philodendron scandens var. cubense,Philodendron isertianum,Philodendron scandens subsp. scandens,Philodendron pittieri,Philodendron miduhoi,Philodendron microphyllum,Philodendron scandens subsp. cubense,Philodendron harlowii,Philodendron oxyprorum,Philodendron scandens f. micans,Philodendron acrocardium,Philodendron scandens var. cuspidatum,Philodendron scandens subsp. prieurianum,Philodendron scandens subsp. isertianum",
    distributions:
      "Belize,Bolivia,Brazil North,Brazil Northeast,Brazil South,Brazil Southeast,Cayman Is.,Central American Pac,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,El Salvador,Guatemala,Honduras,Jamaica,Leeward Is.,Mexico Central,Mexico Gulf,Mexico Northeast,Mexico Southeast,Mexico Southwest,Nicaragua,Panamá,Peru,Puerto Rico,Suriname,Trinidad-Tobago,Venezuela,Windward Is.,Bangladesh,Seychelles,French Guiana,Guyana",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHHE17",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:77170908-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/7228286",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en:
      "https://en.wikipedia.org/wiki/Philodendron hederaceum var. hederaceum",
  },
  {
    id: "165593",
    scientific_name: "Philodendron imbe",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "",
    author: "Schott ex Kunth.",
    bibliography:
      "Enumeratio Plantarum Omnium Hucusque Cognitarum 3: 50. 1841. (Enum. Pl.)",
    common_name: "Philodendron",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Calostigma imbe,Caladium imbe,Philodendron callifolium",
    distributions: "",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHIM5",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo: "",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/7515063",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron imbe",
  },
  {
    id: "165594",
    scientific_name: "Philodendron lingulatum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1855",
    author: "(L.) K.Koch",
    bibliography: "Index Seminum (B, Berolinensis) 1855(App.): 2 (1855)",
    common_name: "Treelover",
    family_common_name: "Arum family",
    image_url:
      "http://d2seqvvyy3b8p2.cloudfront.net/b462e5315dbb46ec2d4157fef062b0b8.jpg",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Forb/herb, Vine",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Arum lingulatum,Philodendron swartzianum,Monstera lingulata,Philodendron karstenianum var. dispar,Philodendron dispar",
    distributions:
      "Dominican Republic,Leeward Is.,Netherlands Antilles,Puerto Rico,Trinidad-Tobago,Windward Is.",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHLI3",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:1027729-2",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2871047",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron lingulatum",
  },
  {
    id: "165596",
    scientific_name: "Philodendron ornatum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1853",
    author: "Schott",
    bibliography: "Oesterr. Bot. Wochenbl. 3: 378 (1853)",
    common_name: "Philodendron",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/60d99e35df590d498fef4d291490b01f1577ca81",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Philodendron dolosum,Philodendron imperiale,Philodendron rubens,Zantedeschia asperata,Philodendron muschlerianum,Philodendron asperatum,Philodendron tobagense",
    distributions:
      "Bolivia,Brazil North,Brazil Northeast,Brazil Southeast,Colombia,Ecuador,French Guiana,Guyana,Peru,Suriname,Trinidad-Tobago,Venezuela,Puerto Rico",
    common_names: "Philodendron",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHOR8",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87918-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Philodendron ornatum Schott",
    url_gbif: "https://www.gbif.org/species/2871136",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron ornatum",
  },
  {
    id: "223713",
    scientific_name: "Zamioculcas zamiifolia",
    rank: "species",
    genus: "Zamioculcas",
    family: "Araceae",
    year: "1905",
    author: "(G.Lodd.) Engl.",
    bibliography: "Pflanzenr., IV, 23B: 305 (1905)",
    common_name: "Zz plant",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/6de84e81df9c71bdfae240b26d013494dd4bf7ad",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Zamioculcas loddigesii,Zamioculcas lanceolata,Caladium zamiifolium",
    distributions: "Kenya,KwaZulu-Natal,Malawi,Mozambique,Tanzania,Zimbabwe",
    common_names: "ZZ Plant,Fern arum,Aroid Palm,Arum Fern",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104727",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:89402-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Zamioculcas zamiifolia (Lodd.) Engl.",
    url_gbif: "https://www.gbif.org/species/2869014",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Zamioculcas",
  },
  {
    id: "165597",
    scientific_name: "Philodendron pinnatifidum",
    rank: "species",
    genus: "Philodendron",
    family: "Araceae",
    year: "1829",
    author: "(Jacq.) Schott",
    bibliography: "Wiener Z. Kunst 3: 780 (1829)",
    common_name: "Comb-leaf philodendron",
    family_common_name: "Arum family",
    image_url:
      "http://d2seqvvyy3b8p2.cloudfront.net/6cf02eaf1026448594d3d19e320e1639.jpg",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine, Forb/herb",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Caladium pinnatifidum,Philodendron pinnatifidum var. virescens,Philodendron pinnatifidum var. rubropunctatum,Philodendron rubropunctatum",
    distributions: "Brazil North,Venezuela,Cuba",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=PHPI7",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87937-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2870665",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Philodendron pinnatifidum",
  },
  {
    id: "157552",
    scientific_name: "Monstera adansonii",
    rank: "species",
    genus: "Monstera",
    family: "Araceae",
    year: "1830",
    author: "Schott",
    bibliography: "Wiener Z. Kunst 4: 1028 (1830)",
    common_name: "Adanson's monstera",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/dcb4298d9abfa3a5adb1d2673e3280e571a41c92",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Calla dracontium,Monstera jacquini,Dracontium pertusum,Calla pertusa,Monstera adansonii var. adansonii",
    distributions:
      "Brazil Northeast,Brazil South,Brazil Southeast,Brazil West-Central,Colombia,Costa Rica,Ecuador,French Guiana,Guyana,Honduras,Leeward Is.,Mexico Southwest,Netherlands Antilles,Nicaragua,Panamá,Peru,Suriname,Trinidad-Tobago,Venezuela,Windward Is.,Puerto Rico,Belize,Bolivia,Brazil North",
    common_names: "Tarovine,Swiss-cheese-plant,Adanson's monstera",
    url_usda: "https://plants.usda.gov/core/profile?symbol=MOAD",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87464-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Monstera adansonii Schott",
    url_gbif: "https://www.gbif.org/species/2868136",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Monstera adansonii",
  },
  {
    id: "157554",
    scientific_name: "Monstera deliciosa",
    rank: "species",
    genus: "Monstera",
    family: "Araceae",
    year: "1849",
    author: "Liebm.",
    bibliography: "Vidensk. Meddel. Naturhist. Foren. Kjøbenhavn 1: 19 (1849)",
    common_name: "Tarovine",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/e0526a4477c3b1b2c0b21e79d3ad563748a7ca4d",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "Vine, Forb/herb",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Philodendron pertusum,Monstera lennea,Monstera deliciosa var. borsigiana,Monstera borsigiana,Monstera tacanaensis,Tornelia fragrans,Monstera deliciosa var. sierrana,Philodendron anatomicum",
    distributions:
      "Costa Rica,Guatemala,Honduras,Mexico Gulf,Mexico Southeast,Mexico Southwest,Nicaragua,Panamá,Ascension,Bangladesh,Cook Is.,Korea,Seychelles,Society Is.,Trinidad-Tobago",
    common_names:
      "Fruit-salad-plant,Monstera,Swiss-cheese-plant,Cut-leaf-philodendron,Mexican-breadfruit,Tarovine,Swiss cheese plant,Windowleaf,Delicious monster,Split Leaf Philodendron,Split-leaf philodendron,Swiss-cheese plant,Window plant,Ceriman,Fruit salad plant,Harpon,Mexican breadfruit,Pine fruit tree",
    url_usda: "https://plants.usda.gov/core/profile?symbol=MODE",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:87478-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Monstera deliciosa Liebm.",
    url_gbif: "https://www.gbif.org/species/2868241",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Monstera deliciosa",
  },
  {
    id: "277585",
    scientific_name: "Begonia maculata",
    rank: "species",
    genus: "Begonia",
    family: "Begoniaceae",
    year: "1820",
    author: "Raddi",
    bibliography: "Alc. Sp. Rett. Piant. Bras.: 406 (1820)",
    common_name: "Polkadot Begonia",
    family_common_name: "Begonia family",
    image_url:
      "https://bs.floristic.org/image/o/6a90e0f01a6c9c1144c200a0298606f2593fa1f3",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Gaerdtia maculata,Begonia argyrostigma,Begonia maculata var. argentea,Begonia maculata f. argentea,Begonia dichroa,Begonia aculeata,Begonia corallina,Gaerdtia argentea",
    distributions:
      "Brazil Southeast,Argentina Northeast,Cuba,Dominican Republic,Mexico Gulf,Mexico Northeast,Mexico Southeast",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/3400563",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:105130-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Begonia maculata Raddi",
    url_gbif: "https://www.gbif.org/species/7303475",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Begonia maculata",
  },
  // {
  //   id: "165590",
  //   scientific_name: "Philodendron hederaceum var. oxycardium",
  //   rank: "var",
  //   genus: "Philodendron",
  //   family: "Araceae",
  //   year: "2002",
  //   author: "Croat (Schott)",
  //   bibliography:
  //     "R. Govaerts & D. G. Frodin, World checkl. bibliogr. Araceae 388.  2002  (Ann. Missouri Bot. Gard. 84:464.  1997, nom. inval.)",
  //   common_name: "Vilevine",
  //   family_common_name: "Arum family",
  //   image_url: "",
  //   flower_color: "",
  //   flower_conspicuous: "",
  //   foliage_color: "",
  //   foliage_texture: "",
  //   fruit_color: "",
  //   fruit_conspicuous: "",
  //   fruit_months: "",
  //   bloom_months: "",
  //   ground_humidity: "",
  //   growth_form: "",
  //   growth_habit: "Vine, Forb/herb",
  //   growth_months: "",
  //   growth_rate: "",
  //   edible_part: "",
  //   vegetable: "false",
  //   edible: "false",
  //   light: "",
  //   soil_nutriments: "",
  //   soil_salinity: "",
  //   anaerobic_tolerance: "",
  //   atmospheric_humidity: "",
  //   average_height_cm: "",
  //   maximum_height_cm: "",
  //   minimum_root_depth_cm: "",
  //   ph_maximum: "",
  //   ph_minimum: "",
  //   planting_days_to_harvest: "",
  //   planting_description: "",
  //   planting_sowing_description: "",
  //   planting_row_spacing_cm: "",
  //   planting_spread_cm: "",
  //   synonyms: "Philodendron oxycardium,Philodendron scandens subsp. oxycardium",
  //   distributions: "Honduras,Mexico Gulf,Mexico Northeast,Mexico Southwest",
  //   common_names: "",
  //   url_usda: "https://plants.usda.gov/core/profile?symbol=PHHE17",
  //   url_tropicos: "",
  //   url_tela_botanica: "",
  //   url_powo:
  //     "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:20007818-1",
  //   url_plantnet: "",
  //   url_gbif: "https://www.gbif.org/species/2871005",
  //   url_openfarm: "",
  //   url_catminat: "",
  //   url_wikipedia_en:
  //     "https://en.wikipedia.org/wiki/Philodendron hederaceum var. oxycardium",
  // },
  {
    id: "154631",
    scientific_name: "Maranta leuconeura",
    rank: "species",
    genus: "Maranta",
    family: "Marantaceae",
    year: "1874",
    author: "É.Morren",
    bibliography: "Ann. Hort. Belge Étrangère 24: 323 (1874)",
    common_name: "Prayerplant",
    family_common_name: "Prayer-Plant family",
    image_url:
      "https://bs.floristic.org/image/o/2d84d9e058ef190dcaa5cbe4de88f66f1d080764",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Maranta depressa,Maranta kerchoveana,Maranta leuconeura var. massangeana,Maranta fascinator,Maranta leuconeura var. erythroneura,Maranta massangeana",
    distributions:
      "Brazil Northeast,Brazil Southeast,Brazil West-Central,Colombia,Mexico Gulf",
    common_names: "Prayerplant,Ten-commandments",
    url_usda: "https://plants.usda.gov/core/profile?symbol=MALE7",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:797361-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Maranta leuconeura E.Morren",
    url_gbif: "https://www.gbif.org/species/2761337",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Maranta depressa",
  },
  {
    id: "220758",
    scientific_name: "Anthurium clarinervium",
    rank: "species",
    genus: "Anthurium",
    family: "Araceae",
    year: "1952",
    author: "Matuda",
    bibliography: "Anales Inst. Biol. Univ. Nac. México 22: 375 (1952)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/529eb82beee30f48917a519968d1141f0d923828",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Mexico Southeast",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2101357",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:15185-2",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Anthurium clarinervium Matuda",
    url_gbif: "https://www.gbif.org/species/2872501",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Anthurium clarinervium",
  },
  {
    id: "223519",
    scientific_name: "Syngonium wendlandii",
    rank: "species",
    genus: "Syngonium",
    family: "Araceae",
    year: "1858",
    author: "Schott",
    bibliography: "Oesterr. Bot. Z. 8: 178 (1858)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/032e85c480273f5ed2ad5b9df4e328e2dc46d1e6",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "",
    distributions: "Costa Rica,Jawa",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104512",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:89164-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Syngonium wendlandii Schott",
    url_gbif: "https://www.gbif.org/species/2867865",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Syngonium wendlandii",
  },
  {
    id: "345556",
    scientific_name: "Syngonium podophyllum var. peliocladum",
    rank: "var",
    genus: "Syngonium",
    family: "Araceae",
    year: "1982",
    author: "Croat (Schott)",
    bibliography:
      "Croat TB (1981) A Revision of Syngonium (Araceae). Annals of the Missouri Botanical Garden 68(4): 565. doi: 10.2307/2398892.",
    common_name: "American evergreen",
    family_common_name: "Arum family",
    image_url: "",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms: "Syngonium peliocladum",
    distributions: "Costa Rica,Panamá",
    common_names: "",
    url_usda: "https://plants.usda.gov/core/profile?symbol=SYPO",
    url_tropicos: "",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:921593-1",
    url_plantnet: "",
    url_gbif: "https://www.gbif.org/species/2867868",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en:
      "https://en.wikipedia.org/wiki/Syngonium podophyllum var. peliocladum",
  },
  {
    id: "223261",
    scientific_name: "Scindapsus pictus",
    rank: "species",
    genus: "Scindapsus",
    family: "Araceae",
    year: "1842",
    author: "Hassk.",
    bibliography: "Tijdschr. Natuurl. Gesch. Physiol. 9: 164 (1842)",
    common_name: "",
    family_common_name: "Arum family",
    image_url:
      "https://bs.floristic.org/image/o/14ba1c21a40dc9104af65ccd720501a7d4565384",
    flower_color: "",
    flower_conspicuous: "",
    foliage_color: "",
    foliage_texture: "",
    fruit_color: "",
    fruit_conspicuous: "",
    fruit_months: "",
    bloom_months: "",
    ground_humidity: "",
    growth_form: "",
    growth_habit: "",
    growth_months: "",
    growth_rate: "",
    edible_part: "",
    vegetable: "false",
    edible: "false",
    light: "",
    soil_nutriments: "",
    soil_salinity: "",
    anaerobic_tolerance: "",
    atmospheric_humidity: "",
    average_height_cm: "",
    maximum_height_cm: "",
    minimum_root_depth_cm: "",
    ph_maximum: "",
    ph_minimum: "",
    planting_days_to_harvest: "",
    planting_description: "",
    planting_sowing_description: "",
    planting_row_spacing_cm: "",
    planting_spread_cm: "",
    synonyms:
      "Pothos argyraeus,Pothos argenteus,Scindapsus argyraeus,Scindapsus pothoides",
    distributions:
      "Bangladesh,Borneo,Jawa,Malaya,Philippines,Sulawesi,Sumatera,Thailand",
    common_names: "",
    url_usda: "",
    url_tropicos: "http://legacy.tropicos.org/Name/2104283",
    url_tela_botanica: "",
    url_powo:
      "http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:88905-1",
    url_plantnet:
      "https://identify.plantnet.org/species/the-plant-list/Scindapsus pictus Hassk.",
    url_gbif: "https://www.gbif.org/species/2873745",
    url_openfarm: "",
    url_catminat: "",
    url_wikipedia_en: "https://en.wikipedia.org/wiki/Scindapsus pictus",
  },
];
